[phases.setup]
nixPkgs = ["php81", "php81Extensions.mysqli", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "php -S 0.0.0.0:$PORT public/index.php"
